services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=patient-service'
      - 'POSTGRES_PASSWORD=docker'
      - 'POSTGRES_USER=local'
    ports:
      - '5432:5432'
