spring:
  application:
    name: patient-service
  flyway:
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/patient-service
    username: local
    password: docker
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: validate
#  sql:
#    init:
#      mode: always

server:
  port: 4000
